+++
title = "📝Clojure Exception: 例外"
lastmod = 2022-10-22T14:53:44+09:00
tags = ["WIKI", "Clojure", "Exception"]
draft = false
+++

Clojureにおける例外処理やエラーハンドリングについてまとめ.

-   up: [📂Clojure Core Languages]({{< relref "20220112142936.md" >}})
-   links.
    -   [Clojure - Clojureを学ぼう - フロー制御](https://japan-clojurians.github.io/clojure-site-ja/guides/learn/flow#_%E4%BE%8B%E5%A4%96)
-   refs.
    -   [🔖Exceptions]({{< relref "20220305075933.md#5c863837-2d4a-457c-9566-ed1748d49e38" >}})
    -   [📝Clojure Java Interop]({{< relref "20220117172324.md" >}})
    -   [📝Java Exception: 例外]({{< relref "20220731122944.md" >}})


## Clojure Exception Basics {#7419fe}

Javaの仕組みを使う. したがってJavaの知識があるとbetter.

Clojureはそもそも[🔖検査例外]({{< relref "20220305075933.md#eb196932-5c4a-48a5-b415-ec2bef0f7aed" >}})のハンドリングが強制されない. 本当に必要なときのみに書けばいい. そのためJavaコードのようにメンテが不自由な汚いコードにならない.

Clojureの例外について書かれている記事は少ないものの, 以下の記事はけっこうな分量だけどClojureの例外の話題を網羅的にいろいろ書いてる.

[Exceptions in Clojure](https://grishaev.me/en/clj-book-exceptions/)

例外をそもそも発生させないように表明プログラミング[📝Clojure spec]({{< relref "20220323030746.md" >}})も検討.


## Clojure Exception Syntax {#cd078e}

Javaのようにtry/catch/finallyが利用できる.

```clojure
(try
  (/ 2 1)
  (catch ArithmeticException e
    "divide by zero")
  (finally
    (println "cleanup")))
```


### throw/ex-info/ex-data/ex-message {#fe6f9400-fbd5-4bb8-a572-d827bdd809d1}

throwシンタックスで例外を引数にとり例外を発生させる.

-   例外はJavaのクラスで作成できる(Exception. )

Javaの仕組みでなくex-infoをつかうとClojureの文法で書ける. いいかえるとMapを渡せる.

-   Clojureの記法でex-infoはmessageとmapを受取リ例外を発生させる.
-   Clojureの記法でex-dataはex-infoで入力したmapを展開する.

<!--listend-->

```clojure
(try
  (throw (ex-info "bad" {:a 1 :b 2}))
  (catch clojure.lang.ExceptionInfo e
    (prn "caught" e)))
```

ex-messageが行メッセージ, ex-dataが詳細情報.

```clojure
(try
  (let [response (http/post
                   "http://localhost:8080/v1/leads"
                   {:form-params {:foo "somethingBad"}})]
    (log/info "This is the response" response))
  (catch Exception e
    (log/error (str "Oops! " (ex-message e)))
    (log/error (str "Because! " (ex-data e))))
```

---

ex-infoで作成された例外でければJavaの例外なのでJavaの仕組みで情報にアクセスする.

-   (.getMessage ex): エラーメッセージ取得.
-   (.getCause ex): 例外クラス取得.

ref. [Throwableクラスのメソッドまとめ]({{< relref "20220731122944.md#c2a27197-35c1-4652-a9d4-158c2a17b30d" >}})


## with-open: リソース開放 {#23cf63}


## 連続的なプロシージャ呼び出しのエラーハンドリングどうするか問題 {#39688d}

Clojureでシステムの外部とやりとりをするときに，ライブラリを使って一連の動作をするシーンがよくある. このとき, 例外処理をどうするか問題. とくにRESP API呼び出しやDBとの通信などで頻発する.

```clojure
(try
   (let [value (func-that-throws)]
      (act-on-value value))
   (catch Exception e
      (log/error e "func-that-throws failed")))
```

threading-macroをカスタムするようにRailway oriented programming?で記述するほうほうと, try-catchとifを用いてゴリゴリ処理する方法があるようだ.

ref. [Clojure とエラーハンドリング at 2021 - Qiita](https://qiita.com/MeguruMokke/items/530159edf0c41a9df6b1)

手続き的な処理をletにずらずら書いていくのはどうも違和感がある(個人的な感想). そうするとスレッディングマクロでbodyに書いていくスタイルはよりClojureらしくてコードの見た目はよい. しかし仕組みがdefaultでClojureに組み込まれていないので汎用的ではない. 手続きが数個に過ぎないならばtryとletとif, そうでなければrailwayを使えばいいかな.


### Railway oriented programming(鉄道指向プログラミング) {#146d42dd-cd7b-4ce3-a8ac-113d791d0834}

鉄道指向プログラミングとは、F# で有名だったプログラミングスタイル. 関数の返り値に正常系の結果 result とそれ以外のパターン err のタプル [result, err] を想定し、実行フローの各プロセスで得られる err が nil でない時 Early-Return をかける方式. (ScalaやHaskellでも合った気がする).

-   refs.
    -   [Railway oriented programming, clojure and exception handling: why and how?](https://medium.com/appsflyer/railway-oriented-programming-clojure-and-exception-handling-why-and-how-89d75cc94c58)

---

さらに, Javaの関数を呼び出すときにライブラリが例外を挙げずにNullを返すときは **some->** というスレッディングマクロを使う方法もClojureのガイドにあった.

ref. [some-> - Threading Macros Guide](https://clojure.org/guides/threading_macros#_some_some_and_cond)


### try-catch and if-let {#826a20}

tryとletをつかって愚直に書く. コードは汚くなるものの実装も理解もこっちは容易.

ref. [🔎if-let は処理の結果による分岐でつかう]({{< relref "20220116081924.md#cf8a7205-5993-4091-af92-a611dd48fd38" >}})

---

try-letというマクロを提供するライブラリもある.

-   refs.
    -   [clojure - How to handle exceptions that occur in let bindings or body - Stack Overflow](https://stackoverflow.com/questions/20335760/how-to-handle-exceptions-that-occur-in-let-bindings-or-body)
    -   [GitHub - rufoa/try-let: Better exception handling for Clojure let expressions](https://github.com/rufoa/try-let)


### 🤔そもそもConsistentを考慮してプログラミングするべきなのか {#d1adfc}

Clojureは並列プログラミングを強く意識してトランザクションという概念もあるくらいなので一連のオペレーションの途中でエラーが失敗したらその一連の処理自体そのものを失敗させるように作るべきなのかもしれない. つまりConsistent, 一貫性という概念.


## slingshot: Enhanced throw and catch for Clojure {#2e6ef68b-b405-489c-8194-17a5e54f3b6d}

ref. [GitHub - scgilardi/slingshot](https://github.com/scgilardi/slingshot)

Clojureは基本的にJavaの例外の仕組みを利用するが, さらにClojureに合わせてカスタマイズしたライブラリ.

たとえば [clj-http]({{< relref "20220209102028.md#13a79f1f-0d95-4f2a-8c4c-b77c4ed69be1" >}}) では HTTP Responseが正常終了以外の場合はこのインスタンスを返すため, slingshotに合わせたエラーハンドリングが期待される.

**try+** と **thorw+** という２つのマクロを提供.

try+で囲まれたカッコ内だと, 隠しMap変数である&throw-contextが参照できる. (:throwable &throw-context)でThrowableオブジェクトが取得できる.

> :object       the caught object;
> :message      the message, from .getMessage;
> :cause        the cause, from .getCause;
> :stack-trace  the stack trace, from .getStackTrace;
> :throwable    the caught object;

catchは第１引数にselector, 第２引数にthrow+で投げたオブジェクトを受け取る. 第２引数は分配束縛によって分解する例をよく見る.

```clojure
   (catch [:type :tensor.parse/bad-tree] {:keys [tree hint]}
      (log/error "failed to parse tensor" tree "with hint" hint)
      (throw+))
```

predicateを関数にすればより詳細な判定がかける.

ref. [Exceptions in Clojure](https://grishaev.me/en/clj-book-exceptions/#exceptions-and-predicates)


## Clojure例外のトピック {#8afb1f}


### ✅REPLで例外と戦う {#74a15a93-ec59-4331-8c2f-75f72d71cfe6}

\*eとpstを覚えよう.

**clojure.core/\*e** という変数に最後に発生したエラーが格納されている. clojure.coreなのでREPLから\*eを叩けばすぐに参照できる.

clojure.repl/pstは \*eのスタックトレースを出力する. またclojure.repl/root-causeはスタックトレースのrootとその階層を指定して出力.

```clojure
(require '[clojure.repl :refer :all])

(pst)
(root-cause (pst) 3)
```


### ⚙pcoll pattern on Clojure {#896dfae0-53c2-4dad-b89c-334bf587fd29}

関数呼び出しをtry-catchで包む方法.

```clojure
(defn pcall [f & args]
  (try
    [true (apply f args)]
    (catch Exception e [false e])))
```

ref. [pcoll pattern in clojure http request]({{< relref "20220209102028.md#3f097ce3-22de-4fa6-b151-0e9a6f2d905d" >}})

関数呼び出しのラッパー関数を作成するのはよく見かけるパターン. さらにフレームワークのミドルウェアとして組み込んだり. pcallというよりもwrapとかmiddlewareとかhandlerというキーワードとともに現れることが多いかも. pcallのprocedure callはhandler wrapper.

-   [Part6: TODO アプリを組み上げる — エラーをうまく処理する](https://ayato-p.github.io/clojure-beginner/intro_web_development/part6_build_up_our_app.html#id12)
    -   slingshotをつかったハンドリング例(ja).
-   [Ringアプリケーションで例外をいい感じにハンドリングする方法(Ductでの解説も含む) - Uzabase for Engineers](https://tech.uzabase.com/entry/2019/10/07/190000)
-   [Handling Exceptions with Middleware in Clojure | 8th Light](https://8thlight.com/blog/mike-knepper/2015/05/19/handling-exceptions-with-middleware-in-clojure.html)
    -   wrap-exceptionというカスタムwrapperと [ring-json]({{< relref "20220118092453.md#b55a2c8e-8f19-4719-9014-8bf43fedb0a8" >}}) の組み合わせ.


### ✅Clojureでヌルポ例外どうするか問題 {#62417123-8cd2-4cf0-ad19-6873542758b7}

Clojureは[🔖動的型付け言語]({{< relref "20220310123730.md#dbdb1d84-3358-4cdc-80ea-5178673130f6" >}})の力を手に入れた結果, [ヌルポ]({{< relref "20221021091329.md#0f927f6d-85b2-4211-9cf0-366e1a0b2365" >}})の呪いにかかった.

nilにアクセスしてヌルポにならない方法はこっちにまとめる.

[nilのハンドリングまとめ]({{< relref "20220302101805.md#0fbf4219-4020-4829-ae01-f057df406c59" >}})

ヌルポが発生したときの例外処理をここでまとめる.

ヌルポが発生したら握りつぶして運用続行 or アプリ停止のどちらかが必要. ヌルポは想定外の動作なので開発中とか個人レベルのアプリならばアプリを落として調査して解消したほうがいい.

いずれにしろ, catch NullpointerEcetpionをするときはstacktraceをログするときの用途に留める(=握りつぶさない).


## <span class="org-todo todo _">🔗</span> References {#d95867}

-
